### ISSUE TITLE
SonarQube 7.7 version- Run Code Analysis failing for ColdFusion 1.7.1 plugin

### ISSUE THREAD

**Issue by amoldagaonkar** [stepstone-tech/sonar-coldfusion#26]
Hello Team,
We are trying to evaluate the ColdFusion plugin in our SonarQube Test instance and we have installed the jar file in the plugin folder for SonarQube Test server file system.
We have create a pipeline in Azure DevOps with 3 steps of sonarqube and tried executing the build pipeline. But it is failing in Run Code Analysis task with the below error.

##[error]ERROR: Error during SonarQube Scanner execution
##[error]org.picocontainer.injectors.AbstractInjector$UnsatisfiableDependenciesException: com.stepstone.sonar.plugin.coldfusion.ColdFusionSensor has unsatisfied dependency 'class org.sonar.api.profiles.RulesProfile' for constructor 'public com.stepstone.sonar.plugin.coldfusion.ColdFusionSensor(org.sonar.api.batch.fs.FileSystem,org.sonar.api.profiles.RulesProfile)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@45667d98:151<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@25aca718:483<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@70f85235:78<|
org.picocontainer.injectors.AbstractInjector$UnsatisfiableDependenciesException: com.stepstone.sonar.plugin.coldfusion.ColdFusionSensor has unsatisfied dependency 'class org.sonar.api.profiles.RulesProfile' for constructor 'public com.stepstone.sonar.plugin.coldfusion.ColdFusionSensor(org.sonar.api.batch.fs.FileSystem,org.sonar.api.profiles.RulesProfile)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@45667d98:151<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@25aca718:483<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@70f85235:78<|
##[error]at org.picocontainer.injectors.ConstructorInjector.getGreediestSatisfiableConstructor(ConstructorInjector.java:191)
at org.picocontainer.injectors.ConstructorInjector.getGreediestSatisfiableConstructor(ConstructorInjector.java:191)
##[error]at org.picocontainer.injectors.ConstructorInjector.getGreediestSatisfiableConstructor(ConstructorInjector.java:110)
at org.picocontainer.injectors.ConstructorInjector.access$100(ConstructorInjector.java:51)
at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:331)
at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
at org.picocontainer.injectors.ConstructorInjector.getGreediestSatisfiableConstructor(ConstructorInjector.java:110)
at org.picocontainer.injectors.ConstructorInjector.access$100(ConstructorInjector.java:51)
at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:331)
at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)

Regards,
Amol Dagaonkar.

**Comment by gvstsai** [comment]
Hello All,

Any update on the above query? We are looking resolution for the above query? What are the supported versions of SonarQube for this "ColdFusion 1.7.1" plugin.

Regards,
Sai

**Comment by svinky** [comment]
+1

**Comment by tommywo** [comment]
SonarQube 7.7 is supported in v2.0.0
